PokerApp/Models/Carta.cs
namespace PokerApp.Models
{
    public class Carta
    {
        public int Valor { get; set; }
        public string Palo { get; set; }
    }
}

PokerApp/ViewModels/ErrorViewModel.cs
using System;

namespace PokerApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PokerApp/ViewModels/PlayerViewModel.cs
using PokerApp.Models;
using System.Collections.Generic;

namespace PokerApp.ViewModels
{
    public class PlayerViewModel
    {
        public string Name { get; set; }
        public List<Carta> Cartas { get; set; }
        public int Puntaje { get; set; }
        public string Estrategia { get; set; }
    }
}

PokerApp/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using PokerApp.Contracts;
using PokerApp.ViewModels;
using System.Collections.Generic;

namespace PokerApp.Controllers
{
    public class GameController : Controller
    {
        private IDealer _dealer;

        public GameController(IDealer dealer)
        {
            _dealer = dealer;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Resultado(List<PlayerViewModel> players)
        {
            _dealer.RepartirCartas(players);
            _dealer.GetPlayersStrategies(players);

            var positionsTable = _dealer.MakePositionsTable(players);
            return View(positionsTable);
        }

    }
}

PokerApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PokerApp.Models;

namespace PokerApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PokerApp/Views/Game/Index.cshtml
@{
    ViewData["Title"] = "Poker game";
}

<div class="row">
    <div class="col-6">
        <form method="post" action="/Game/Resultado">
            @for (var i = 0; i < 5; i++) { 
                <div class="form-group">
                    <label>Jugador @(i + 1):</label>
                    <input type="text" name="players[@i].Name" class="form-control" placeholder="Nombre del jugador @(i + 1)" required autocomplete="off"/>
                </div>
            }
            <button type="submit" class="btn btn-block btn-primary">Jugar!</button>
        </form>
    </div>
</div>

PokerApp/Views/Game/Resultado.cshtml
@model Dictionary<int, IGrouping<int, PokerApp.ViewModels.PlayerViewModel>>


<div class="row">
    <div class="col-12">
        <h1>Tabla de posiciones</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>Posición</th>
                    <th>Jugador</th>
                    <th>Estrategía</th>
                </tr>
            </thead>
            <tbody>
                @for (var i = 0; i < Model.Count; i++)
                {
                    <tr>
                        <td>@(i + 1) </td>
                        <td>
                            <ul>
                                @foreach (var player in Model.ToList()[i].Value.ToList())
                                {
                                    <li>
                                        @player.Name
                                        <br />
                                        Cartas:
                                        <ul>
                                            @foreach (var carta in player.Cartas)
                                            {
                                                <li>@carta.Valor de @carta.Palo</li>
                                            }
                                        </ul>
                                    </li>
                                }
                            </ul>
                        </td>

                        <td>@Model.ToList()[i].Value.ToList()[0].Estrategia</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PokerApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PokerApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PokerApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Game" asp-action="Index">PokerApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Poker</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PokerApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>